---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgclusters.radondb.com
  labels:
    vendor: radondb
spec:
  group: radondb.com
  names:
    kind: Pgcluster
    listKind: PgclusterList
    plural: pgclusters
    singular: pgcluster
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clustername: { type: string }
            ccpimage: { type: string }
            ccpimagetag: { type: string }
            database: { type: string }
            exporterport: { type: string }
            name: { type: string }
            pgbadgerport: { type: string }
            PrimaryStorage: { type: object }
            port: { type: string }
            userlabels: { type: object }
        status:
          properties:
            state: { type: string }
            message: { type: string }
