---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgreplicas.radondb.com
  labels:
    vendor: radondb
spec:
  group: radondb.com
  names:
    kind: Pgreplica
    listKind: PgreplicaList
    plural: pgreplicas
    singular: pgreplica
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        status:
          properties:
            state: { type: string }
            message: { type: string }
